[project]
name = "hyperliquid-multisig"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = ["hyperliquid-python-sdk>=0.10.1"]

[tool.pyright]
venvPath = "."
venv = ".venv"
